branch-defaults:
  master:
    environment: Dataqualitychecker-env
    group_suffix: null
environment-defaults:
  Dataqualitychecker-env:
    branch: null
    repository: null
  dataquality-dev:
    branch: null
    repository: null
global:
  application_name: dataqualitychecker
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
